# GitHub Actions Workflow for CD of Terraform Infrastructure

name: Deploy 3-Tier Architecture using Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Initialise Terraform
        run: terraform init
      
      - name: Validate Terraform configuration
        run: terraform validate
      
      - name: Plan Terraform changes
        run: terraform plan -var "db_password=${{ secrets.DB_PASSWORD }}" -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -var "db_password=${{ secrets.DB_PASSWORD }}" -auto-approve tfplan

      - name: Destroy infrastructure
        run: terraform destroy -var "db_password=${{ secrets.DB_PASSWORD }}" -auto-approve

